import Foundation

public enum FileMintAbout {
    public static let copyright = "XiaoDaiGua-Ray"
    public static let developers = ["XiaoDaiGua-Ray", "GPT-Astra"]
    public static let projectURL = URL(string: "https://github.com/FileMintApp/FileMint")!
    public static let privacyURL = projectURL.appendingPathComponent("blob/main/PRIVACY.md")
    public static let licenseURL = projectURL.appendingPathComponent("blob/main/LICENSE")
    public static let releasesURL = projectURL.appendingPathComponent("releases/latest")
}

/// FileMint's release workflow accepts three-component stable versions only.
public struct ReleaseVersion: Comparable, Equatable, Sendable, CustomStringConvertible {
    public let major: Int
    public let minor: Int
    public let patch: Int

    public init?(_ value: String) {
        let number = value.hasPrefix("v") ? String(value.dropFirst()) : value
        let parts = number.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 3, parts.allSatisfy({ part in
            !part.isEmpty && part.utf8.allSatisfy { (48...57).contains($0) }
                && (part.count == 1 || part.first != "0")
        }), let major = Int(parts[0]), let minor = Int(parts[1]), let patch = Int(parts[2]) else { return nil }
        self.major = major
        self.minor = minor
        self.patch = patch
    }

    public var description: String { "\(major).\(minor).\(patch)" }

    public static func < (lhs: Self, rhs: Self) -> Bool {
        (lhs.major, lhs.minor, lhs.patch) < (rhs.major, rhs.minor, rhs.patch)
    }
}

public struct AppUpdate: Equatable, Sendable {
    public let version: ReleaseVersion
    public let releaseURL: URL
    public let downloadURL: URL
    public let checksumURL: URL
    public let size: Int64
    public let digest: String?
    public var fileName: String { downloadURL.lastPathComponent }
}

public enum UpdateValidationError: Error, Equatable {
    case invalidVersion
    case invalidRelease
    case missingAssets
    case untrustedURL
    case invalidChecksum
    case checksumMismatch
}

public enum AppUpdatePolicy {
    public static let latestReleaseURL = URL(string: "https://api.github.com/repos/FileMintApp/FileMint/releases/latest")!
    public static let maximumInstallerSize: Int64 = 1_073_741_824

    public static func availableUpdate(from data: Data, currentVersion: String) throws -> AppUpdate? {
        guard let current = ReleaseVersion(currentVersion) else { throw UpdateValidationError.invalidVersion }
        let release: GitHubRelease
        do { release = try JSONDecoder().decode(GitHubRelease.self, from: data) }
        catch { throw UpdateValidationError.invalidRelease }
        guard !release.draft, !release.prerelease else { throw UpdateValidationError.invalidRelease }
        guard let version = ReleaseVersion(release.tag_name) else { throw UpdateValidationError.invalidVersion }
        let expectedPage = FileMintAbout.projectURL.appendingPathComponent("releases/tag/\(release.tag_name)")
        guard release.html_url == expectedPage else { throw UpdateValidationError.untrustedURL }
        guard version > current else { return nil }

        let name = "FileMint-\(version).dmg"
        let installers = release.assets.filter { $0.name == name }
        let checksums = release.assets.filter { $0.name == "\(name).sha256" }
        guard installers.count == 1, checksums.count == 1,
              let installer = installers.first, let checksum = checksums.first,
              installer.state == "uploaded", checksum.state == "uploaded",
              (1...maximumInstallerSize).contains(installer.size),
              (1...4096).contains(checksum.size) else { throw UpdateValidationError.missingAssets }
        let base = FileMintAbout.projectURL.appendingPathComponent("releases/download/\(release.tag_name)")
        guard installer.browser_download_url == base.appendingPathComponent(name),
              checksum.browser_download_url == base.appendingPathComponent("\(name).sha256") else {
            throw UpdateValidationError.untrustedURL
        }
        var digest: String?
        if let value = installer.digest {
            guard value.hasPrefix("sha256:"), let hash = normalizedHash(String(value.dropFirst(7))) else {
                throw UpdateValidationError.invalidChecksum
            }
            digest = hash
        }
        return AppUpdate(version: version, releaseURL: expectedPage,
                         downloadURL: installer.browser_download_url, checksumURL: checksum.browser_download_url,
                         size: installer.size, digest: digest)
    }

    /// Accept only the portable shasum output generated by package_release.sh.
    public static func checksum(from data: Data, fileName: String) throws -> String {
        guard data.count <= 4096, let text = String(data: data, encoding: .utf8) else {
            throw UpdateValidationError.invalidChecksum
        }
        let lines = text.split(whereSeparator: \.isNewline)
        guard lines.count == 1, let line = lines.first, line.count > 65,
              let hash = normalizedHash(String(line.prefix(64))) else { throw UpdateValidationError.invalidChecksum }
        let suffix = line.dropFirst(64)
        guard suffix.first == " " || suffix.first == "\t" else { throw UpdateValidationError.invalidChecksum }
        var name = suffix.trimmingCharacters(in: .whitespaces)
        if name.hasPrefix("*") { name.removeFirst() }
        guard name == fileName else { throw UpdateValidationError.invalidChecksum }
        return hash
    }

    public static func verifyChecksum(_ actual: String, expected: String, assetDigest: String?) throws {
        guard let actual = normalizedHash(actual), let expected = normalizedHash(expected),
              actual == expected else { throw UpdateValidationError.checksumMismatch }
        if let assetDigest, normalizedHash(assetDigest) != actual { throw UpdateValidationError.checksumMismatch }
    }

    /// Release asset redirects carry expiring query parameters on GitHub's CDN.
    public static func allowsNetworkURL(_ url: URL) -> Bool {
        guard url.scheme == "https", url.user == nil, url.password == nil,
              url.fragment == nil, url.port == nil || url.port == 443 else { return false }
        switch url.host {
        case "api.github.com": return url == latestReleaseURL
        case "github.com":
            return url.path.hasPrefix("/FileMintApp/FileMint/releases/download/") && url.query == nil
        case "release-assets.githubusercontent.com", "objects.githubusercontent.com", "github-releases.githubusercontent.com":
            return true
        default: return false
        }
    }

    private static func normalizedHash(_ value: String) -> String? {
        guard value.utf8.count == 64, value.utf8.allSatisfy({
            (48...57).contains($0) || (65...70).contains($0) || (97...102).contains($0)
        }) else { return nil }
        return value.lowercased()
    }
}

private struct GitHubRelease: Decodable {
    let tag_name: String
    let html_url: URL
    let draft: Bool
    let prerelease: Bool
    let assets: [GitHubAsset]
}

private struct GitHubAsset: Decodable {
    let name: String
    let browser_download_url: URL
    let size: Int64
    let state: String
    let digest: String?
}
